# Generated by Django 4.1.7 on 2023-04-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
