# Generated by Django 4.1.7 on 2023-04-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_rename_userproile_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
