# Generated by Django 4.1.7 on 2023-04-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
