# Generated by Django 4.1.7 on 2023-04-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_alter_post_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
