# Generated by Django 4.1.4 on 2023-04-21 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liked_posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.post'),
        ),
    ]
